config/routes.rb
::Refinery::Application.routes.draw do
  resources :members, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :members, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/member.rb
class Member < ActiveRecord::Base

  acts_as_indexed :fields => [:first_name, :last_name, :email, :unique_identifier]

  validates :unique_identifier, :presence => true, :uniqueness => true
  
  default_scope order(:last_name)
end

app/controllers/admin/members_controller.rb
module Admin
  class MembersController < Admin::BaseController

    crudify :member,
            :title_attribute => 'first_name',
            :xhr_paging => true,
            :sortable => false,
            :order => 'last_name ASC'

  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_filter :find_all_members
  before_filter :find_page

  def index
    redirect_to root_url
  end

  def show
    redirect_to root_url
  end

protected

  def find_all_members
    @members = Member.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/members").first
  end

end

app/views/admin/members/_actions.html.erb
<ul>
  <% if Admin::MembersController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_members_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_member_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::MembersController.sortable? and Member.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Members"),
                 admin_members_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Members"),
                 admin_members_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/members/_form.html.erb
<%= form_for [:admin, @member] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @member,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :first_name -%>
    <%= f.text_field :first_name -%>
  </div>
  
  <div class='field'>
    <%= f.label :last_name -%>
    <%= f.text_field :last_name  -%>
  </div>
  
  <div class='field'>
    <%= f.label :email -%>
    <%= f.text_field :email  -%>
  </div>
  
  <div class='field'>
    <%= f.label :unique_identifier -%>
    <%= f.text_field :unique_identifier  -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.members.member'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @member.first_name)
              } %>
<% end -%>

app/views/admin/members/_member.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(member) -%>">
  <span class='title'>
    <%= member.last_name %>, <%= member.first_name %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_member_path(member),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_member_path(member),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => member.first_name),
        :method => :delete %>
  </span>
</li>

app/views/admin/members/_members.html.erb
<%= will_paginate @members %>
<%= render :partial => "sortable_list" %>

app/views/admin/members/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @members.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'members' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/members/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'member', :collection => @members %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/members/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/members/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::MembersController.sortable? and Member.count > 1 %>

app/views/admin/members/new.html.erb
<%= render :partial => "form" %>

app/views/members/index.html.erb
<% content_for :body_content_left do %>
  <ul id="members">
    <% @members.each do |member| %>
      <li>
        <%= link_to member.first_name, member_path(member) %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/members/show.html.erb
<% content_for :body_content_title do %>
  <%= @member.first_name %>
<% end %>

<% content_for :body_content_left do %>
  <section>
    <h1>First Name</h1>
    <p>
      <%=raw @member.first_name %>
    </p>
  </section>
  <section>
    <h1>Last Name</h1>
    <p>
      <%=raw @member.last_name %>
    </p>
  </section>
  <section>
    <h1>Email</h1>
    <p>
      <%=raw @member.email %>
    </p>
  </section>
  <section>
    <h1>Unique Identifier</h1>
    <p>
      <%=raw @member.unique_identifier %>
    </p>
  </section>
<% end %>

<% content_for :body_content_right do %>
  <aside>
    <h2><%= t('.other') %></h2>
    <ul id="members">
      <% @members.each do |member| %>
        <li>
          <%= link_to member.first_name, member_path(member) %>
        </li>
      <% end %>
    </ul>
  </aside>
<% end %>

<%= render :partial => "/shared/content_page" %>